'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),os=require('os'),path=require('path'),vm=require('vm'),http=require('http'),{spawn,spawnSync}=require('child_process'),{createRequire}=require('module');
const root=path.resolve(__dirname,'..'),source=fs.readFileSync(path.join(root,'app/server.js'),'utf8'),realRequire=createRequire(path.join(root,'app/server.js'));
function sessionFixture(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'tht-portable-unit-'));const c={__dirname:path.join(root,'app'),require:n=>n==='./config'?{dataDir:dir,load:()=>({LLM_BASE_URL:'https://example.com',LLM_MODEL:'test',DEEPSEEK_API_KEY:'synthetic'})}:realRequire(n),process:{...process,env:{...process.env,THT_PORT:'47824'}},Buffer,console,setInterval:()=>0,clearInterval(){},setTimeout,clearTimeout,fetch:async()=>({json:async()=>({choices:[{message:{content:JSON.stringify({highlights:[{text:'Meeting point'}],todos:[],factchecks:[{claim:'A fictional number',verdict:'unsure',note:'Not verified'}]})}}]})}),AbortSignal};vm.createContext(c);vm.runInContext(source.slice(0,source.indexOf('function buildExportState()'))+'\nthis.Session=Session;this.local=isLocalReq;',c);return {c,dir};}
test('portable session keeps audio through unavailable provider and restart; manual edit survives',()=>{const {c,dir}=sessionFixture();const s=new c.Session('synthetic',{},{});s.transcript=[{text:'张三 says hello'}];s.sendAudio(Buffer.alloc(32000,1));s.applyTranscriptEdits([{index:0,originalText:'张三 says hello',text:'张山 says hello'}]);s.closeAudio();const restored=new c.Session('synthetic',{},{});assert.equal(restored.transcript[0].text,'张山 says hello');assert.equal(restored.transcript[0].originalText,'张三 says hello');assert.equal(fs.statSync(restored.audioPath).size,32000);assert(restored.audioPath.startsWith(dir));restored.closeAudio();fs.rmSync(dir,{recursive:true,force:true});});
test('translation covers captions as well as summary and checks while preserving source',async()=>{const html=fs.readFileSync(path.join(root,'web/index.html'),'utf8'),a=html.indexOf('  async function translateSession(){'),b=html.indexOf('  function renderMeetingTasks()',a);let rendered=0;const s={transcript:[{text:'Hello tomorrow'}],highlights:[],todos:[],factchecks:[],summary:''};const c={cur:s,translating:false,macOnline:true,cfg:{},ui:'zh',needsTranslation:t=>!!t,hubAPI:async()=>({strings:['明天你好']}),note(){},persist(){},resetSigs(){},render(){rendered++;},scheduleTranslation(){},Date};vm.createContext(c);vm.runInContext(html.slice(a,b)+'\nthis.run=translateSession;',c);await c.run();assert.equal(s.i18n.zh.map['Hello tomorrow'],'明天你好');assert.equal(s.transcript[0].text,'Hello tomorrow');assert.equal(rendered,1);});
test('rolling triage returns highlights and uncertain checks without blocking audio',async()=>{const{c,dir}=sessionFixture();const s=new c.Session('triage',{},{LLM_BASE_URL:'https://example.com',LLM_MODEL:'test',DEEPSEEK_API_KEY:'synthetic'});s.transcript=[{at:1,text:'This is a sufficiently long synthetic meeting statement for the incremental analysis to operate.'}];s.charsSinceTriage=120;const p=s.runTriage();s.sendAudio(Buffer.alloc(64));await p;assert(s.highlights.some(h=>h.text==='Meeting point'));assert.equal(s.factchecks[0].verdict,'unsure');assert.equal(fs.statSync(s.audioPath).size,64);s.closeAudio();fs.rmSync(dir,{recursive:true,force:true});});
test('server rejects cross-origin, proxy and hostile Host bootstrap access',()=>{const{c,dir}=sessionFixture();const req={socket:{remoteAddress:'127.0.0.1'},headers:{host:'127.0.0.1:47824'}};assert(c.local(req));for(const headers of [{host:'evil.example:47824'},{...req.headers,origin:'https://evil.example'},{...req.headers,'sec-fetch-site':'cross-site'},{...req.headers,'x-forwarded-for':'1.1.1.1'}])assert.equal(c.local({...req,headers}),false);fs.rmSync(dir,{recursive:true,force:true});});
test('fresh backend serves UI and saves full corrected record without Feishu or model key',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'tht-portable-e2e-'));const port=await new Promise(r=>{const s=http.createServer();s.listen(0,'127.0.0.1',()=>{const p=s.address().port;s.close(()=>r(p));});});const child=spawn(process.execPath,[path.join(root,'app/server.js')],{env:{...process.env,THT_DATA_DIR:dir,THT_PORT:String(port),THT_TEST:'1'},stdio:'ignore'});const base='http://127.0.0.1:'+port;
 try{let ready=false;for(let i=0;i<40;i++){try{ready=(await fetch(base+'/health')).ok;}catch{}if(ready)break;await new Promise(r=>setTimeout(r,50));}assert(ready);
 const setup=await(await fetch(base+'/setup')).json();assert.equal(setup.ready,false);assert(!JSON.stringify(setup).includes('RELAY_TOKEN'));assert.equal(fs.statSync(path.join(dir,'settings.json')).mode&0o077,0);
 assert.equal((await fetch(base+'/tinghuitai/index.html')).status,200);assert.equal((await fetch(base+'/tinghuitai/bootstrap.js',{headers:{Origin:'https://evil.example'}})).status,403);
 const session={id:'portable-test',title:'Synthetic meeting',start:Date.now(),transcript:[{text:'张山 next week',originalText:'张三 next week',edited:true}],todos:[],uiLang:'zh'};
 const saved=await fetch(base+'/archive',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({target:'local',session})});assert.equal(saved.status,200);
 let jobs=[];for(let i=0;i<80;i++){jobs=(await(await fetch(base+'/meeting-status')).json()).jobs;if(jobs[0]&&['done','partial','error'].includes(jobs[0].status))break;await new Promise(r=>setTimeout(r,100));}
 assert.equal(jobs[0].status,'partial');assert.equal(jobs[0].fullTextVerified,true);assert.equal(jobs[0].archiveTarget,'local');assert(!jobs[0].docId);
 const record=await(await fetch(base+'/meeting-result?id=portable-test')).json();assert.equal(record.transcript[0].text,'张山 next week');assert.equal(record.transcript[0].originalText,'张三 next week');assert(fs.readdirSync(path.join(dir,'archives',jobs[0].key)).some(n=>n.endsWith('.md')));
 }finally{child.kill();await new Promise(r=>child.once('exit',r));fs.rmSync(dir,{recursive:true,force:true});}
});
test('Volc final frames reach captions, duplicates are ignored, numbered speaker is retained',()=>{const{c,dir}=sessionFixture();const s=new c.Session('captions',{},{}),messages=[];s.broadcast=m=>messages.push(m);const body=Buffer.from(JSON.stringify({result:{utterances:[{text:'Hello tomorrow',definite:true,utterance_id:1,speaker:'2'}]}})),head=Buffer.from([0x11,0x90,0x10,0]),size=Buffer.alloc(4);size.writeUInt32BE(body.length);const frame=Buffer.concat([head,size,body]);s.onVolc(frame);s.onVolc(frame);assert.equal(s.transcript.length,1);assert.equal(s.transcript[0].text,'Hello tomorrow');assert.equal(messages.filter(m=>m.type==='final').length,1);assert.equal(messages[0].speaker,'2');s.closeAudio();fs.rmSync(dir,{recursive:true,force:true});});
